INSERT INTO articulos (CodigoArticulo, NombreArticulo, IdCategoria, CantidadExistencia, PrecioVigente, TotalValorado, TipoInventario, Descripcion, FechaVencimiento) VALUES 
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Té Dharamsala', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cerveza tibetana Barley', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Sirope de regaliz', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Especias Cajun del chef Anton', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Mezcla Gumbo del chef Anton', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Mermelada de grosellas de la abuela', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Peras secas orgánicas del tío Bob', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Salsa de arándanos Northwoods', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Buey Mishi Kobe', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Pez espada', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso Cabrales', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso Manchego La Pastora', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Algas Konbu', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cuajada de judías', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Salsa de soja baja en sodio', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Postre de merengue Pavlova', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cordero Alice Springs', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Langostinos tigre Carnarvon', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Pastas de té de chocolate', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Mermelada de Sir Rodneys', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Bollos de Sir Rodneys', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Pan de centeno crujiente estilo Gustafs', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Pan fino', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Refresco Guaraná Fantástica', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Crema de chocolate y nueces NuNuCa', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Ositos de goma Gumbär', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Chocolate Schoggi', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Col fermentada Rössle', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Salchicha Thüringer', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Arenque blanco del noroeste', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso gorgonzola Telino', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso Mascarpone Fabioli', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso de cabra', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cerveza Sasquatch', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cerveza negra Steeleye', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Escabeche de arenque', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Salmón ahumado Gravad', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Vino Côte de Blaye', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Licor verde Chartreuse', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Carne de cangrejo de Boston', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Crema de almejas estilo Nueva Inglaterra', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Tallarines de Singapur', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Café de Malasia', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Azúcar negra Malacca', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Arenque ahumado', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Arenque salado', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Galletas Zaanse', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Chocolate holandés', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Regaliz', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Chocolate blanco', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Manzanas secas Manjimup', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cereales para Filo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Empanada de carne', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Empanada de cerdo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Paté chino', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Gnocchi de la abuela Alicia', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Raviolis Angelo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Caracoles de Borgoña', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Raclet de queso Courdavault', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Camembert Pierrot', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Sirope de arce', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Tarta de azúcar', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Sandwich de vegetales', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Bollos de pan de Wimmer', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Salsa de pimiento picante de Luisiana', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Especias picantes de Luisiana', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cerveza Laughing Lumberjack', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Barras de pan de Escocia', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso Gudbrandsdals', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cerveza Outback', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Crema de queso Fløtemys', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso Mozzarella Giovanni', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Caviar rojo', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Queso de soja Longlife', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Cerveza Klosterbier Rhönbräu', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Licor Cloudberry', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL),
((ObtenerCodigoProducto( (SELECT FLOOR( RAND() * (15-1+1) + 1 )) )) , 'Salsa verde original Frankfurter', (SELECT FLOOR( RAND() * (15-1+1) + 1 )), 0, 0, 0, 'P', NULL, NULL);


